# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: telemetry.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'telemetry.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0ftelemetry.proto\x12\ttelemetry\"\x99\x01\n\x07ImuData\x12\x0f\n\x07\x61\x63\x63\x65l_x\x18\x01 \x01(\x02\x12\x0f\n\x07\x61\x63\x63\x65l_y\x18\x02 \x01(\x02\x12\x0f\n\x07\x61\x63\x63\x65l_z\x18\x03 \x01(\x02\x12\x0e\n\x06gyro_x\x18\x04 \x01(\x02\x12\x0e\n\x06gyro_y\x18\x05 \x01(\x02\x12\x0e\n\x06gyro_z\x18\x06 \x01(\x02\x12\r\n\x05mag_x\x18\x07 \x01(\x02\x12\r\n\x05mag_y\x18\x08 \x01(\x02\x12\r\n\x05mag_z\x18\t \x01(\x02\"@\n\x07GpsData\x12\x10\n\x08latitude\x18\x01 \x01(\x01\x12\x11\n\tlongitude\x18\x02 \x01(\x01\x12\x10\n\x08\x61ltitude\x18\x03 \x01(\x01\"\xaa\x01\n\x0fTelemetryPacket\x12\x11\n\tdevice_id\x18\x01 \x01(\t\x12\x17\n\x0fsequence_number\x18\x02 \x01(\x04\x12\x14\n\x0ctimestamp_ms\x18\x03 \x01(\x04\x12\x13\n\x0btemperature\x18\x04 \x01(\x02\x12\x1f\n\x03gps\x18\x05 \x01(\x0b\x32\x12.telemetry.GpsData\x12\x1f\n\x03imu\x18\x06 \x01(\x0b\x32\x12.telemetry.ImuData\"b\n\x0b\x41\x63kResponse\x12\x17\n\x0fsequence_number\x18\x01 \x01(\x04\x12\x18\n\x10server_timestamp\x18\x02 \x01(\x04\x12\x0f\n\x07success\x18\x03 \x01(\x08\x12\x0f\n\x07message\x18\x04 \x01(\t2\xa0\x01\n\x10TelemetryService\x12\x43\n\rSendTelemetry\x12\x1a.telemetry.TelemetryPacket\x1a\x16.telemetry.AckResponse\x12G\n\x0fStreamTelemetry\x12\x1a.telemetry.TelemetryPacket\x1a\x16.telemetry.AckResponse(\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'telemetry_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_IMUDATA']._serialized_start=31
  _globals['_IMUDATA']._serialized_end=184
  _globals['_GPSDATA']._serialized_start=186
  _globals['_GPSDATA']._serialized_end=250
  _globals['_TELEMETRYPACKET']._serialized_start=253
  _globals['_TELEMETRYPACKET']._serialized_end=423
  _globals['_ACKRESPONSE']._serialized_start=425
  _globals['_ACKRESPONSE']._serialized_end=523
  _globals['_TELEMETRYSERVICE']._serialized_start=526
  _globals['_TELEMETRYSERVICE']._serialized_end=686
# @@protoc_insertion_point(module_scope)
